defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: optuna

  noise_dir: /placeholder/for/noise
  noise_dir: /home/user114/yunsik/dataset/datasets_fullband/noise_fullband_resampled 
  noise_train: dataset/noise_train.txt 
  noise_valid: dataset/noise_dev.txt 
  rir_dir: /placeholder/for/rir
  rir_dir: /home/user114/yunsik/dataset/datasets_fullband/impulse_responses
  rir_train: dataset/rir_train.txt 
  rir_valid: dataset/rir_dev.txt
  rir_test: dataset/rir_test.txt
  test_augment_numb: 2

# Dataset related
sampling_rate: 16000
segment: 64000
stride: 32000
shift: 32000

# noise augmentation for train
train_noise:
  snr_range: [-15, 20]
  reverb_proportion: 0.75
  target_dB_FS: -25
  target_dB_FS_floating_value: 10
  silence_length: 0.2

# noise augmentation for valid
valid_noise:
  snr_range: [-15, 10]
  reverb_proportion: 0.5
  target_dB_FS: -25
  target_dB_FS_floating_value: 0
  silence_length: 0.2
  deterministic: true

# noise augmentation for test
# Caution! To many SNR steps will cause OOM error
test_noise:
  snr_step: [0]
  reverb_proportion: 0.5
  target_dB_FS: -25
  target_dB_FS_floating_value: 0
  silence_length: 0.2
  deterministic: true

batch_size: 16
batch_size_valid: 1
epochs: 200

eval_every: 100  # compute test metrics every so epochs
eval_stt: true

# Loss related
loss:
  l1_loss: 1.0
  multistftloss:
    weight: 1.0
    factor_mag: 0.5
    factor_sc: 0.5
    fft_sizes: [1024, 2048, 512]
    hop_sizes: [120, 240, 50]
    win_lengths: [600, 1200, 240]
    window: hann_window
  # metricganloss:
  #   ndf: 16
  #   factor_disc: 1.0
  #   factor_gen: 0.1
  #   fft_size: 512
  #   hop_size: 256
  #   win_length: 512
  #   window: hann_window

# Optimization related
lr: 3e-4
optim: adam
betas: [0.9, 0.99]
clip_grad_norm: 

# Logging and printing, and does not impact training
device: cuda
num_prints: 10
num_workers: 5
ddp:
  master_addr: localhost
  master_port: 12355

checkpoint: true
checkpoint_file: checkpoint.th
continue_from: 
samples_dir: samples
log_dir: tensorbd

# Other stuff
seed: 2039

# Hydra config
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}

  job:
    chdir: true

  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  # sweeper:
  #   _target_: hydra_plugins.hydra_optuna_sweeper.optuna.OptunaSweeper
  #   direction: minimize  # valid_loss를 최소화하는 것이 목표
  #   study_name: masking_optimization
  #   storage: null
  #   n_trials: 100  # 총 시도 횟수
  #   n_jobs: 1 # 동시에 실행할 job의 수
  #   sampler:
  #     _target_: optuna.samplers.TPEsampler # 베이즈 최적화를 위한 TPE 샘플러
  #     seed: 1234

  #   sweep:
  #     dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  #     subdir: ${hydra.job.num}
  #   mode:
  #     - model/masking # masking.yaml을 사용하도록 지정

  #   launcher:
  #     params:
  #       model.param.TSCB_numb: choice(2, 4, 6)
  #       model.param.ffn_dim: choice(16, 32, 64)
  #       model.param.depthwise_conv_kernel_size: choice(15, 23, 31)
  #       model.param.dropout: range(0.1, 0.4)