defaults:
  - _self_
  - model: bafnetplus
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

dset:
  noise_dir: /home/user114/yunsik/dataset/datasets_fullband/noise_fullband_resampled 
  noise_train: dataset/noise_train.txt 
  noise_valid: dataset/noise_dev.txt 
  noise_test: dataset/noise_test.txt
  rir_dir: /home/user114/yunsik/dataset/datasets_fullband/impulse_responses
  rir_train: dataset/rir_train.txt 
  rir_valid: dataset/rir_dev.txt
  rir_test: dataset/rir_test.txt
  test_augment_numb: 1

# Dataset related
sampling_rate: 16000
segment: 64000
stride: 32000
shift: 32000

# noise augmentation for train
train_noise:
  snr_range: [-15, 20]
  reverb_proportion: 0.75
  target_dB_FS: -25
  target_dB_FS_floating_value: 10
  silence_length: 0.2

# noise augmentation for valid
valid_noise:
  snr_range: [-15, 10]
  reverb_proportion: 0.5
  target_dB_FS: -25
  target_dB_FS_floating_value: 0
  silence_length: 0.2
  deterministic: true

# noise augmentation for test
test_noise:
  snr_step: [-10, 0, 10]
  reverb_proportion: 0.5
  target_dB_FS: -25
  target_dB_FS_floating_value: 0
  silence_length: 0.2
  deterministic: true


batch_size: 32
batch_size_valid: 1
epochs: 100

eval_every: 100  # compute test metrics every so epochs
eval_stt: true
eval_only:
enhance_only:

# Loss related
loss:
  l1_loss: 1.0
  multistftloss:
    weight: 1.0
    factor_mag: 0.5
    factor_sc: 0.5
    fft_sizes: [1024, 2048, 512]
    hop_sizes: [120, 240, 50]
    win_lengths: [600, 1200, 240]
    window: hann_window

# Optimization related
lr: 3e-4
optim: adam
betas: [0.9, 0.99]
clip_grad_norm: 1.0

# Logging and printing, and does not impact training
device: cuda
num_prints: 10
num_workers: 5
ddp:
  master_addr: localhost
  master_port: 12355

checkpoint: true
checkpoint_file: checkpoint.th
continue_from:
samples_dir: samples
log_dir: tensorbd

# Other stuff
seed: 2039

# Hydra config
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs
    subdir: ${hydra.job.override_dirname}

  job:
    chdir: true

  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr
