defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

dset:
  noise_dir: /home/work/yskim/dataset/datasets_fullband/noise_fullband_16k
  noise_train: dataset/noise_train.txt 
  noise_valid: dataset/noise_dev.txt 
  noise_test: dataset/noise_test.txt
  rir_dir: /home/work/yskim/dataset/datasets_fullband/impulse_responses_16k
  rir_train: dataset/rir_train.txt 
  rir_valid: dataset/rir_dev.txt
  rir_test: dataset/rir_test.txt
  test_augment_numb: 2

# Dataset related
sampling_rate: 16000
segment: 64000
stride: 32000
shift: 32000
n_fft: 400
hop_size: 100
win_size: 400
compress_factor: 0.3


# noise augmentation for train
train_noise:
  snr_range: [-15, 20]
  reverb_proportion: 0.0
  target_dB_FS: -25
  target_dB_FS_floating_value: 10
  silence_length: 0.2

# noise augmentation for valid
valid_noise:
  snr_range: [-15, 10]
  reverb_proportion: 0.0
  target_dB_FS: -25
  target_dB_FS_floating_value: 0
  silence_length: 0.2
  deterministic: true

# noise augmentation for test
# Caution! To many SNR steps will cause OOM error
test_noise:
  snr_step: [0]
  reverb_proportion: 0.0
  target_dB_FS: -25
  target_dB_FS_floating_value: 0
  silence_length: 0.2
  deterministic: true

batch_size: 4
batch_size_valid: 1
epochs: 200

eval_every: 100  # compute test metrics every so epochs
eval_stt: true

# Loss related
loss:
  magnitude: 0.9
  phase: 0.3
  complex: 0.1
  consistency: 0.05
  metric: 0.05

# Optimization related
lr: 5e-4
lr_decay: 0.99
optim: adamW
betas: [0.8, 0.99]

# Logging and printing, and does not impact training
device: cuda
num_prints: 10
num_workers: 5
ddp:
  master_addr: localhost
  master_port: 12355

continue_from: 
samples_dir: samples
log_dir: tensorbd
save_code: true

# Other stuff
seed: 2039

# Hydra config
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}

  job:
    chdir: true

  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr